Repository sofastack/sofa-hessian, pull requests merged in 2019-03, with the labels that each got.

#35 Update serialize.blacklist
  src/main/resources/security/serialize.blacklist
Labels: security

#40 Code clean up.
  src/main/java/com/alipay/hessian/ClassNameResolverBuilder.java
  src/main/java/com/alipay/hessian/Constants.java
  src/main/java/com/alipay/hessian/internal/InternalNameBlackListFilter.java
  src/main/java/com/caucho/hessian/io/ContextSerializerFactory.java
  src/test/java/com/caucho/hessian/io/ContextSerializerFactoryTest.java
Labels: enhancement

#41 Upgrade version to 4.0.3.
  pom.xml
Labels: version
