Repository sofastack/sofa-hessian, pull requests merged in 2020-04, with the labels that each got.

#55 feat:clear black list cache
  src/main/java/com/alipay/hessian/NameBlackListFilter.java
  src/main/java/com/caucho/hessian/io/SerializerFactory.java
Labels: cla:yes, size/S

#56 Fix ci on master.
  src/main/java/com/caucho/hessian/io/SerializerFactory.java
  tools/ci/.travis.settings.xml
Labels: bug, cla:yes, size/XS

#57 feat:add another filter
  pom.xml
  src/main/java/com/alipay/hessian/internal/InternalNameBlackListFilter.java
Labels: cla:yes, size/M
