Repository sofastack/sofa-hessian, pull requests merged in 2023-08, with the labels that each got.

#92 Sofaboot 4.0 support
  .github/workflows/build.yml
Labels: cla:yes, size/XS

#94 optimized code
  src/main/java/com/caucho/hessian/io/Hessian2Input.java
  src/main/java/com/caucho/hessian/io/JavaDeserializer.java
Labels: cla:yes, size/XS, First-time contributor

#98 fix: deser log
  src/main/java/com/caucho/hessian/io/throwable/ThrowableDeserializer.java
Labels: bug, cla:yes, size/XS

#99 Optimized code
  src/main/java/com/caucho/burlap/client/MicroBurlapOutput.java
  src/main/java/com/caucho/hessian/io/AbstractDeserializer.java
  src/main/java/com/caucho/hessian/io/AbstractListDeserializer.java
  src/main/java/com/caucho/hessian/io/AbstractMapDeserializer.java
  src/main/java/com/caucho/hessian/micro/MicroHessianOutput.java
  src/main/java/com/caucho/hessian/server/HessianSkeleton.java
Labels: cla:yes, size/S, First-time contributor

#93 Sofaboot 4.0 support
  pom.xml
  src/main/java/com/caucho/hessian/io/AbstractFieldAdaptorDeserializer.java
  src/main/java/com/caucho/hessian/io/AbstractFieldAdaptorSerializer.java
  src/main/java/com/caucho/hessian/io/JavaDeserializer.java
  src/main/java/com/caucho/hessian/io/JavaSerializer.java
  src/main/java/com/caucho/hessian/io/SerializerFactory.java
  src/main/java/com/caucho/hessian/io/StackTraceElementDeserializer.java
  src/main/java/com/caucho/hessian/io/ThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/atomic/AtomicDeserializer.java
  src/main/java/com/caucho/hessian/io/atomic/AtomicSerializer.java
  src/main/java/com/caucho/hessian/io/java17/base/JavaCurrencyDeserializer.java
  src/main/java/com/caucho/hessian/io/java17/base/JavaCurrencySerializer.java
  src/main/java/com/caucho/hessian/io/throwable/ReflectThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/StackTraceElementDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/StackTraceElementSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableHelper.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/adapter/EnumConstantNotPresentExceptionDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/adapter/EnumConstantNotPresentExceptionSerializer.java
  src/main/java/com/caucho/hessian/util/ReflectionUtil.java
  src/test/java/com/caucho/hessian/io/java17/base/CurrencyWrapper.java
  src/test/java/com/caucho/hessian/io/java17/base/SerializeCompatibleTest.java
  src/test/java/com/caucho/hessian/io/java17/base/SerializeFactoryWithCurrency.java
  src/test/java/com/caucho/hessian/io/java17/base/SerializeFactoryWithoutCurrency.java
  src/test/java/com/caucho/hessian/io/throwable/ExceptionWrapper.java
  src/test/java/com/caucho/hessian/io/throwable/JDK17SerializeFactory.java
  src/test/java/com/caucho/hessian/io/throwable/MeaninglessEnum.java
  src/test/java/com/caucho/hessian/io/throwable/SelfDefinedException.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeCompatibleSelfTest.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeCompatibleTest.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeFactoryWithoutThrowable.java
  src/test/java/com/caucho/hessian/io/throwable/ThrowableClassTest.java
  src/test/java/com/caucho/hessian/io/throwable/ThrowableJdk17SerializeTest.java
  src/test/java/com/caucho/hessian/test/atomic/AtomicDeserializeTest.java
  src/test/java/com/caucho/hessian/test/atomic/AtomicWrapper.java
  src/test/java/com/caucho/hessian/test/atomic/SerializeCompatibleTest.java
  src/test/java/com/caucho/hessian/test/stacktrace/ExceptionClassTest.java
  src/test/java/com/caucho/hessian/test/stacktrace/ExceptionWrapper.java
  src/test/java/com/caucho/hessian/test/stacktrace/SerializeCompatibleTest.java
Labels: cla:yes, size/XXL
