Repository sofastack/sofa-hessian, pull requests merged in 2023-06, with the labels that each got.

#80 fix: locale handle support
  pom.xml
  src/main/java/com/caucho/hessian/io/CalendarHandle.java
  src/main/java/com/caucho/hessian/io/LocaleHandle.java
  src/main/java/com/caucho/hessian/io/SerializerFactory.java
  src/test/java/com/caucho/hessian/test/java8/AbstractWrapper.java
  src/test/java/com/caucho/hessian/test/java8/AsmClassDefineHelper.java
  src/test/java/com/caucho/hessian/test/java8/Java8TimeSerializerTest.java
Labels: bug, cla:yes, size/L, First-time contributor

#84 Fix CVE-2019-9212
  src/main/resources/security/serialize.blacklist
Labels: cla:yes

#86 feat: add release aci for hessian
  .github/workflows/release.yml
Labels: cla:yes, size/M

#87 feat: release workflow
  .github/workflows/release.yml
Labels: cla:yes, size/M

#88 fix: gpg maven plugin
  pom.xml
Labels: bug, cla:yes, size/XS

#89 Sofaboot 4.0 support
  .github/workflows/build.yml
  pom.xml
  src/main/java/com/caucho/hessian/io/AbstractFieldSpecificDeserializer.java
  src/main/java/com/caucho/hessian/io/AbstractFieldSpecificSerializer.java
  src/main/java/com/caucho/hessian/io/JavaDeserializer.java
  src/main/java/com/caucho/hessian/io/JavaSerializer.java
  src/main/java/com/caucho/hessian/io/SerializerFactory.java
  src/main/java/com/caucho/hessian/io/StackTraceElementDeserializer.java
  src/main/java/com/caucho/hessian/io/ThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/atomic/AtomicDeserializer.java
  src/main/java/com/caucho/hessian/io/atomic/AtomicSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/ReflectThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/StackTraceElementDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/StackTraceElementSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableHelper.java
  src/main/java/com/caucho/hessian/io/throwable/ThrowableSerializer.java
  src/main/java/com/caucho/hessian/io/throwable/adapter/EnumConstantNotPresentExceptionDeserializer.java
  src/main/java/com/caucho/hessian/io/throwable/adapter/EnumConstantNotPresentExceptionSerializer.java
  src/main/java/com/caucho/hessian/util/ReflectionUtil.java
  src/test/java/com/caucho/hessian/io/throwable/ExceptionWrapper.java
  src/test/java/com/caucho/hessian/io/throwable/JDK17SerializeFactory.java
  src/test/java/com/caucho/hessian/io/throwable/MeaninglessEnum.java
  src/test/java/com/caucho/hessian/io/throwable/SelfDefinedException.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeCompatibleSelfTest.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeCompatibleTest.java
  src/test/java/com/caucho/hessian/io/throwable/SerializeFactoryWithoutThrowable.java
  src/test/java/com/caucho/hessian/io/throwable/ThrowableClassTest.java
  src/test/java/com/caucho/hessian/io/throwable/ThrowableJdk17SerializeTest.java
  src/test/java/com/caucho/hessian/test/atomic/AtomicDeserializeTest.java
  src/test/java/com/caucho/hessian/test/atomic/AtomicWrapper.java
  src/test/java/com/caucho/hessian/test/atomic/SerializeCompatibleTest.java
  src/test/java/com/caucho/hessian/test/stacktrace/ExceptionClassTest.java
  src/test/java/com/caucho/hessian/test/stacktrace/ExceptionWrapper.java
  src/test/java/com/caucho/hessian/test/stacktrace/SerializeCompatibleTest.java
Labels: cla:yes, size/XXL

#90 Sofaboot 4.0 support
  pom.xml
Labels: cla:yes, size/XS

#91 Add disclaimer
  README.md
Labels: cla:yes, size/S
